### ISSUE TITLE
Continued scheduled notification errors

### ISSUE THREAD

**Issue by tlakhtak** [BIDMCDigitalPsychiatry/LAMP-platform#523]
After the latest update we reset all previously scheduled activities to ensure that they appeared at the correct time, regardless of timezone. However, I am still seeing that on my testing account I receive notifications that do not line up correctly with the scheduled time as per the times I scheduled, or as they are reflected in the feed. For example, today at 12:00pm PST I received this notification for an activity group called 'Evening', despite having scheduled it for 7pm and the Feed also reflecting that it is scheduled for 7pm. The same thing occurred with the Cognitive Games activity, which was scheduled for 8pm but I received the notification at 1 pm
![IMG_2353](https://user-images.githubusercontent.com/82968538/154760903-5e7ca436-d93b-4c14-90d3-e46d66e066c7.PNG)

![IMG_2355](https://user-images.githubusercontent.com/82968538/154760908-8ae82ee0-4bfd-4be7-a852-e7c70cd4f335.PNG)

![IMG_2354](https://user-images.githubusercontent.com/82968538/154753910-526b39e8-08fb-4ffc-a686-5e2dfcd115d5.PNG)

**Comment by jeydude** [comment]
We are also noticing this issue with latest update to our server done yesterday. All our activities times are incorrect now.

**Comment by avaidyam** [comment]
@jeydude Have you manually re-saved activity schedules yet? If so, do the times appear correct in the Feed tab of the app?

**Comment by jeydude** [comment]
I just updated manually to correct time now, let you know the findings.

**Comment by jeydude** [comment]
I have updated the activities schedule time to 4:00 PM Triweekly. Feed tab is showing proper time now.  I did not receive any push notification yet. It is almost 4:10 pm here.

Tried to update few activities, i did not receive any notification yet.

**Comment by jeydude** [comment]
@avaidyam here is my findings, I am working in CST time my current time is around 4:30 PM:

1. If you set your activity schedule time to 7:00 PM or more, then in the Feed tab we do not see your activity that's scheduled activity schedule time to 7:00 PM 
2.  Have a activity schedule time as 10:30 PM daily , but I am receiving push notification at 4:30 PM.

**Comment by jeydude** [comment]
Tried rolling back to older image bidmcdigitalpsychiatry/lamp-server:2021, still same issue,  receiving push notification at 5:00 PM if the activity schedule time is at 11:00 PM.

**Comment by Linoy339** [comment]
@tlakhtak . Can we get the participant id?

**Comment by jeydude** [comment]
Yes, confirmed the push notification appears only at (activity schedule time - GMT difference time) time, even after relogin to the mindLamp app in the iPhone.

We have installed LAMP API server in our server, please let me know if you need any more information. Thanks!

**Comment by jijopulikkottil** [comment]
The timezone issue of local notification mentioned [here](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/417#issuecomment-1040306189) is fixed now. Latest source code is pushed.

**Comment by Linoy339** [comment]
@jeydude . Could you please let us know the LAMP-worker image you are using?

**Comment by jeydude** [comment]
I am using ghcr.io/bidmcdigitalpsychiatry/lamp-server:2022

**Comment by jeydude** [comment]
Here is my yaml

```
version: '3.7'
services:
  server:
    image: ghcr.io/bidmcdigitalpsychiatry/lamp-server:2022
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    environment:
      HTTPS: 'off'
      SCHEDULER: 'on'
      ROOT_KEY: ‘xxxxxxxx’
      CDB: 'http://admin:password@database:5984/'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      PUSH_API_KEY: ‘xxxxxxxxxx’
      DASHBOARD_URL: 'dashboard.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      NATS_SERVER: 'message_queue:4222'
      CACHE_SIZE: 100
    networks:
      - default
      - public
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      labels:
         traefik.enable: 'true'
         traefik.http.routers.lamp_server.entryPoints: 'websecure'
         traefik.http.routers.lamp_server.rule: 'Host(`xxxxxxxxxx`)'
         traefik.http.routers.lamp_server.tls.certresolver: 'default'
         traefik.http.services.lamp_server.loadbalancer.server.port: 3000
         traefik.docker.network: 'public'
      placement:
        constraints:
          - node.role == manager 
  database:
    image: mlpcouchdb
    healthcheck:
      test: curl --fail --silent http://localhost:5984/_up || exit 1
    environment:
      COUCHDB_USER: 'admin'
      COUCHDB_PASSWORD: ‘xxxxxxx’
    volumes:
      - /apps/mindLAMP/data/couchdb:/opt/couchdb/data
    networks:
      - public
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
    ports:
    - "4369:4369/tcp"
    - "5984:5984/tcp"
    - "9100:9100/tcp"
    labels:
      traefik.enable: 'true'
      traefik.http.routers.lamp_database.entryPoints: 'websecure'
      traefik.http.routers.lamp_database.rule: 'Host(`xxxxxxx`)'
      traefik.http.routers.lamp_database.tls.certresolver: 'default'
      traefik.http.services.lamp_database.loadbalancer.server.port: 5984
  cache:
    image: redis:6.0.8-alpine
    healthcheck:
      test: redis-cli ping
    deploy:
      mode: replicated
      update_config:
        order: stop-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
  message_queue:
    image: nats:2.1.9-alpine3.12
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8222/varz || exit 1
    deploy:
      mode: replicated
      update_config:
        order: start-first
        failure_action: rollback
      placement:
        constraints:
          - node.role == manager
networks:
  public:
    external: true
```



Image date for ghcr.io/bidmcdigitalpsychiatry/lamp-server:2022 is 2022-02-14 16:51:40

**Comment by Linoy339** [comment]
@jeydude. This means that you are using native app alone to fire notifications and not included lamp-worker component to do the same. As @jijopulikkottil  said, native app fix for push notifications was done recently and you have to take the new build.

@avaidyam . Can you please mention the  feedback on Lamp-worker exclusion in this yaml file? 
Although, the local notifications is implemented in app side, it won't work as expected, because android won't trigger the notification, if the internet is unavailable. Can you please let us know on this?

**Comment by jijopulikkottil** [comment]
@jeydude The latest build Version 2022.1.13 (304) with "Local notification timezone fix" is available on TestFlight now. https://testflight.apple.com/join/TSpdLc6U

**Comment by saranya-sajeev** [comment]
@avaidyam It is resolved in Android too and is available in beta.

**Comment by jeydude** [comment]
@avaidyam 

I tried with old images (2021, 2022) of ghcr.io/bidmcdigitalpsychiatry/lamp-server none of the helped with timezone issue with push notification messages.

Tried Test Flight version of mindLAMP app, push notification message works fine after using Test Flight version.

**Comment by jeydude** [comment]
@avaidyam currently we have few active studies going on, which study participants will be affected with this push notification issues, can you explain that?

**Comment by avaidyam** [comment]
@jeydude Thanks for the feedback - I'll consider this issue closed, but please add the following to your stack file: 

```yaml
  worker:
    image: ghcr.io/bidmcdigitalpsychiatry/lamp-worker:2022
    environment:
      DASHBOARD_URL: 'dashboard.lamp.digital'
      PORT: '3000'
      NATS_SERVER: 'nats:4222'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      REDIS_HOST: 'redis://message_queue:6379/0'
      PUSH_API_KEY: 'YOUR_API_KEY_HERE'
      DOCKER_ADDR: "127.0.0.1:2375"
      LAMP_SERVER: "YOUR_SERVER_DOMAIN_HERE"
      LAMP_AUTH: "ADMIN_USERNAME:ADMIN_PASSWORD"
      TIMEZONE: 'America/New_York'
      SCHEDULER: 'on'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - public
```

**Comment by er42** [comment]
@avaidyam, unfortunately this issue doesn't appear to be resolved, at least for us. We've been having the same type of notification problems described by @jeydude and others. I've updated our server code using the updated yaml code described above, but we are still getting notifications arriving in UTC rather than local time, regardless of whether we specify `America/New_York` or another timezone in the new yaml.

Confusingly, and perhaps related to another bug (https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/417), the app activities feed does show the intended local times for the notifications, even though the notifications do not arrive at those times. Also, strangely, when recurring surveys are scheduled beginning on the same day during the afternoon, Pacific Time, they do not show up on the feed until the following day. Presumably this is because by afternoon Pacific it is already the next day in UTC; it sounds like the time and date are currently converted/saved in different ways, leading to a mismatch.

We've mostly been testing this using the 2021.10.20 version of the iOS app.

Is it possible to escalate this issue for a more rapid fix and/or roll-back the timezone-related changes to the codebase until an app version with forward/backward compatibility is released? Notifications were working fine for us until week before last. 

We were not aware that any changes to scheduling behavior were planned -- that would have been helpful to know in advance. As it is now, this issue is disrupting data collection for an ongoing study of ours, leading to data loss. From the posts on here, it sounds like we aren't the only ones affected. This bug also has the potential to annoy participants if notifications start arriving in the middle of the night. It seems like the new scheduling code wasn't adequately tested before it was pushed out.

**Comment by jeydude** [comment]
I tried deploying LAMP-Worker image, getting

```
redis connection error Error: connect ECONNREFUSED 10.0.19.5:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '10.0.19.5',
  port: 6379
}
```


Error in Connecting to nats sub server


redis connection error Error: connect ECONNREFUSED 10.0.19.5:6379


    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {


  errno: -111,


  code: 'ECONNREFUSED',


  syscall: 'connect',


  address: '10.0.19.5',


  port: 6379


}

**Comment by avaidyam** [comment]
@jeydude Your Redis service might have a different name (`REDIS_HOST: 'redis://message_queue:6379/0'`). You should change it to `cache` instead of `message_queue`, and instead of `nats` in `NATS_SERVER: 'nats:4222'`, you should use `message_queue`. I had the variables mixed up when I shared my earlier YAML, sorry!

**Comment by avaidyam** [comment]
> Presumably this is because by afternoon Pacific it is already the next day in UTC; it sounds like the time and date are currently converted/saved in different ways, leading to a mismatch.

@er42 This is correct, as identified in #417, the time and date fields are encoded differently (the date field is converted to UTC using the **clinician timezone**) by the dashboard. That will be rectified. 

> We've mostly been testing this using the `2021.10.20` version of the iOS app.

@er42 We're pushing the `2022.2.28` iOS build to app store review today. We expect it to be available later this week or early next week, depending on Apple's review timeline. //cc @jijopulikkottil Please confirm and I'll make a new GitHub Release for `LAMP-core-ios`. 

> Is it possible to escalate this issue for a more rapid fix and/or roll-back the timezone-related changes to the codebase until an app version with forward/backward compatibility is released? Notifications were working fine for us until week before last.

@er42 Unfortunately we're not able to roll it back because the affected code is part of the iOS and Android apps - but it should be rectified quickly. I believe this stems from a feature of the native apps where if push notifications fail to deliver (i.e. no network connection, server issues, etc.) it enables backup notifications that work entirely offline. 

> We were not aware that any changes to scheduling behavior were planned -- that would have been helpful to know in advance. 

@er42 I would be glad to share a roadmap of our upcoming and planned features or bug fixes on [our community forum](https://mindlamp.discourse.group/). Do you have an account there? 

> As it is now, this issue is disrupting data collection for an ongoing study of ours, leading to data loss. From the posts on here, it sounds like we aren't the only ones affected. This bug also has the potential to annoy participants if notifications start arriving in the middle of the night. 

@er42 I completely understand, as this bug has disrupted our (BIDMC's) studies as well. Please accept our apologies for the disruption as we work to have this resolved as our highest priority. 

> It seems like the new scheduling code wasn't adequately tested before it was pushed out.

With the nature of testing between varying frontend, backend, and native app versions, it is difficult to identify and resolve these complex cross-component bugs. However, going forward, **we'll be implementing stricter quality control checks and ensuring legacy behavior and compatibility is preserved in all situations.**

**Comment by jeydude** [comment]
@avaidyam Thanks for the corrections.

here is my corrected yaml for worker
```
  worker:
    image: ghcr.io/bidmcdigitalpsychiatry/lamp-worker:2022
    environment:
      DASHBOARD_URL: 'dashboard.lamp.digital'
      PORT: '3000'
      NATS_SERVER: 'message_queue:4222'
      APP_GATEWAY: 'app-gateway.lamp.digital'
      REDIS_HOST: 'redis://cache:6379/0'
      PUSH_API_KEY: 'YOUR_PUSH_API_KEY_HERE'
      DOCKER_ADDR: '127.0.0.1:2375'
      LAMP_SERVER: 'LAMP API Server HOST NAME'
      LAMP_AUTH: 'API SERVER ADMIN_USERNAME:API SERVER ADMIN_PASSWORD'
      TIMEZONE: 'America/New_York'
      SCHEDULER: 'on'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
      - public
  ```

Now worker component is able to connect to is able to nat sub server, but having another issue

```
Trying to connect redis
server listening in 3000
Connected to redis
Initialized redis queue
Clean all queues...
DONE--CLEANING ALL QUEUE
itializing schedulers...
Connected to nats sub server
Fetching Researchers
FetchError: request to https://romlptestapi.mayo.edu/researcher failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
```

**Comment by avaidyam** [comment]
@jeydude It looks like `UNABLE_TO_VERIFY_LEAF_SIGNATURE` is a TLS (HTTPS) verification failure. If [you add the `NODE_TLS_REJECT_UNAUTHORIZED=0` variable mapping to the `environment` section of the `worker` service](https://stackoverflow.com/a/20100521), does it work?

**Comment by jeydude** [comment]
Thanks @avaidyam after adding ```NODE_TLS_REJECT_UNAUTHORIZED: 0``` at the end of the worker environment, worker component started fine.

I will test the push notification and let you know.

one question:
In the worker stack yaml
I have 
``` volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

is this correct or should it be 
```
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by jeydude** [comment]
oh OK, Thanks!

**Comment by er42** [comment]
Hi @avaidyam, thanks for the clarification on these issues. We will eagerly await the updated iOS app with the bug fix. 

In the meantime, do you or @jijopulikkottil happen to know if this bug is also affecting Android users? I haven't had a chance to test  this on an android phone yet.

If you could point me toward the roadmap on the discourse page, that would be great to be able to anticipate future changes.

**Comment by jijopulikkottil** [comment]
> In the meantime, do you or @jijopulikkottil happen to know if this bug is also affecting Android users?

@er42 Yes, it is also affecting existing Android App version 2021.2.17.
